/* Generated by Yosys 0.8 (git sha1 5706e90) */

(* src = "sample.v:1" *)
module full_adder(xin, yin, cin, sout, cout);
  (* src = "sample.v:5" *)
  wire _0_;
  (* src = "sample.v:5" *)
  wire _1_;
  (* src = "sample.v:4" *)
  wire _2_;
  (* src = "sample.v:2" *)
  input cin;
  (* src = "sample.v:3" *)
  output cout;
  (* src = "sample.v:3" *)
  output sout;
  (* src = "sample.v:2" *)
  input xin;
  (* src = "sample.v:2" *)
  input yin;
  assign sout = _2_ ^(* src = "sample.v:4" *)  cin;
  assign _0_ = xin &(* src = "sample.v:5" *)  yin;
  assign _2_ = xin ^(* src = "sample.v:5" *)  yin;
  assign _1_ = _2_ &(* src = "sample.v:5" *)  cin;
  assign cout = _0_ |(* src = "sample.v:5" *)  _1_;
endmodule
