/* Generated by Yosys 0.8 (git sha1 5706e90) */

(* src = "sample.v:1" *)
module full_adder(A, B, X, carry);
  (* src = "sample.v:5|<techmap.v>:260|<techmap.v>:203" *)
  wire [4:0] _00_;
  wire [4:0] _01_;
  (* src = "sample.v:5|<techmap.v>:260" *)
  wire [4:0] _02_;
  (* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)
  wire _03_;
  (* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)
  wire _04_;
  (* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)
  wire _05_;
  (* src = "sample.v:5|<techmap.v>:260|<techmap.v>:222" *)
  wire _06_;
  (* src = "sample.v:5|<techmap.v>:260|<techmap.v>:229" *)
  wire _07_;
  (* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)
  wire _08_;
  (* src = "sample.v:2" *)
  input [3:0] A;
  (* src = "sample.v:2" *)
  input [3:0] B;
  (* src = "sample.v:3" *)
  output [3:0] X;
  (* src = "sample.v:4" *)
  output carry;
  assign _03_ = _01_[1] &(* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)  _00_[0];
  assign _04_ = _01_[3] &(* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)  _02_[2];
  assign _05_ = _06_ &(* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)  _00_[1];
  assign _06_ = _01_[3] &(* src = "sample.v:5|<techmap.v>:260|<techmap.v>:222" *)  _01_[2];
  assign _07_ = _01_[2] &(* src = "sample.v:5|<techmap.v>:260|<techmap.v>:229" *)  _00_[1];
  assign _00_[1] = _02_[1] |(* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)  _03_;
  assign _08_ = _02_[3] |(* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)  _04_;
  assign carry = _08_ |(* src = "sample.v:5|<techmap.v>:260|<techmap.v>:221" *)  _05_;
  assign _00_[2] = _02_[2] |(* src = "sample.v:5|<techmap.v>:260|<techmap.v>:229" *)  _07_;
  assign X[0] = A[0] ^(* src = "sample.v:5|<techmap.v>:262" *)  B[0];
  assign _01_[1] = A[1] ^(* src = "sample.v:5|<techmap.v>:262" *)  B[1];
  assign _01_[2] = A[2] ^(* src = "sample.v:5|<techmap.v>:262" *)  B[2];
  assign _01_[3] = A[3] ^(* src = "sample.v:5|<techmap.v>:262" *)  B[3];
  assign X[1] = _01_[1] ^(* src = "sample.v:5|<techmap.v>:263" *)  _00_[0];
  assign X[2] = _01_[2] ^(* src = "sample.v:5|<techmap.v>:263" *)  _00_[1];
  assign X[3] = _01_[3] ^(* src = "sample.v:5|<techmap.v>:263" *)  _00_[2];
  assign _00_[0] = A[0] &(* src = "sample.v:5|<techmap.v>:260" *)  B[0];
  assign _02_[1] = A[1] &(* src = "sample.v:5|<techmap.v>:260" *)  B[1];
  assign _02_[2] = A[2] &(* src = "sample.v:5|<techmap.v>:260" *)  B[2];
  assign _02_[3] = A[3] &(* src = "sample.v:5|<techmap.v>:260" *)  B[3];
endmodule
